package com.abc.transactiondemo.mapper;


import com.abc.transactiondemo.bean.User2;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface User2Mapper {
    int deleteByPrimaryKey(Integer id);

    int insert(User2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2
     *
     * @mbggenerated Tue Jan 30 11:23:27 CST 2018
     */
    int insertSelective(User2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2
     *
     * @mbggenerated Tue Jan 30 11:23:27 CST 2018
     */
    User2 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2
     *
     * @mbggenerated Tue Jan 30 11:23:27 CST 2018
     */
    int updateByPrimaryKeySelective(User2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user2
     *
     * @mbggenerated Tue Jan 30 11:23:27 CST 2018
     */
    int updateByPrimaryKey(User2 record);
    
    int truncated();
}