spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mp?kuseSSL=false&serverTimezone=GMT
    username: root
    password: root
logging:
  level:
    com.abc.mybatis.mapper.UserMapper: debug
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml